### ISSUE TITLE
Discord "Streamer Mode" Always on and Audio Sync issue

### ISSUE THREAD

**Issue by masterkaj** [Palakis/obs-ndi#40]
4.01 fixed some of the large issues, but I still have a few problems.  

1.  Discord normally goes into "Streamer Mode" when I open OBS.  However, ever since I installed NDI my Discord is constantly in this mode (even when OBS is closed and I am not streaming).  While Streamer Mode isn't a problem, it points to a underlying issue that NDI is running all the time in the background.  My main concern is immediately after I installed the NDI plugin my mouse felt a little off even with OBS closed.  This issue disappears when I uninstall NDI.

2.  Audio sync on my Twitch stream is a fraction of a second delayed. 

Relevant information:

Using latest version of OBS Studio, Discord, and NDI 4.0.1.  The gaming and streaming pc are hard wired and are capable of pushing full speeds (~112MB/s tested).  I am sending 1080p/30fps over NDI using bicubic downscaling (my native resolution is 1440p).

**Gaming PC:**
- Windows 10 x64 
- i7 2600k @ 4.6ghz 
- 16gb DDR3
- GTX 1080
- Samsung 850 Evo SSD

**Streaming PC:**
- Windows 8.1 x64
- e3-1241 v3
- 16gb DDR3
- GTX 1050
- Intel 520 SSD

**Comment by Palakis** [comment]
Hi @masterkaj 

> Discord normally goes into "Streamer Mode" when I open OBS. However, ever since I installed NDI my Discord is constantly in this mode (even when OBS is closed and I am not streaming).

> it points to a underlying issue that NDI is running all the time in the background

That's weird. Neither the plugin nor the NDI library/runtime spawn any additional process.

> Audio sync on my Twitch stream is a fraction of a second delayed.

Causes for audio sync issues within OBS and/or obs-ndi are hard to pinpoint without detailed information.

Within OBS' engine: audio delay happens because of additional buffering and is notified in the log file with messages like `adding x milliseconds of audio buffering`. Additional buffering can be caused by any source that sends wrong or off-clock timestamps to the engine. Known instances of this are:
- Older versions of the NDI source (obs-ndi prior to 4.0.1)
- OBS' Media Source in some specific cases
- OBS' Audio Input Capture source with "Use Device Timestamps" enabled (some cheap audio devices have improper clocking or clock phase issues. Sending this kind of timestamps to OBS can be devastating)

Regarding obs-ndi's Main Output, you may want to try the latest obs-ndi 4.1 which has improved pixel format conversion code and uses NDI 3.0.

**Comment by masterkaj** [comment]
I fixed my Discord issue by reinstalling OBS.  When installing the new versions do we need to remove the previous version of the plugin and uninstall the previous version of the Newtek NDI Redist beforehand?

**Comment by Palakis** [comment]
Thanks for this review! Btw you may want to test the NDI output again, it much faster now. Tested this right now with 1080p 120fps, resulting in ~20% CPU usage while playing 120fps gameplay footage through a Media Source. Found a tearing in the output though, but managed to fix it and will release a hotfix release soon.

**Comment by theduelistgirl** [comment]
So I can confirm the audio desync is still occurring in 4.1.0 sadly :(  I've been testing various configs options and previous versions of the NDI Plugin (4.1.0 -> 4.0.1 -> 4.1.0, clean installs/reboot each version down/upgrade) and the issue is persistent. The only difference is the desync happens slower on 4.1.0 than it does in 4.0.1.

I have logfiles for the main test I've done with 4.1.0, links below:
Both machines are laptops, connected directly via Gigabit Ethernet w/CAT6.
Gaming PC: https://gist.github.com/aceebc60c5a8652f4c3cb803b5e27086
Streaming PC: https://gist.github.com/35f65ff3a1eb6b5453c1bac600cf6299

**Comment by Palakis** [comment]
Seems like the desync happens on the NDI receiving end. Sync your two computers with NTP time (with Windows' time settings or a more precise app like [NetTime](http://www.timesynctool.com/)) and try again.

**Comment by Chifilly** [comment]
I'd just like to add that I'm having audio sync issues too. I've tries using NetTime on both PC's, I've tried disabling "Use Device Timestamps" and I'm using version 4.1.2 and I still have audio delays. The video is sent immediately (when I change scene, they both fade in perfect synchronisation) but the audio is noticeably out of sync, and I kept getting these messages in the logs:
```
20:28:14.066: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
20:28:14.623: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
20:29:12.953: adding 23 milliseconds of audio buffering, total audio buffering is now 69 milliseconds
20:29:13.514: adding 23 milliseconds of audio buffering, total audio buffering is now 92 milliseconds
```

It seems to always be 23 milliseconds of buffering, and whenever I close and re-open OBS and audio gets sent, it adds another 23 milliseconds of delay

**Comment by Palakis** [comment]
Regarding the issue with Discord's Streamer Mode not turning off: looks like the NDI runtime opens its own sub-processes at some point, which may be detected by Discord as child processes of OBS.
So if Discord doesn't exit Streamer Mode after closing OBS, open Task Manager, look for an NewTek NDI process and kill it.

**Comment by Palakis** [comment]
@masterkaj Closing this, as I get no response from your end. Feel free to comment again here if you still encounter these issues (apart for the audio desync, where discussion happens in #60).
